

server:
  port: 8081
  servlet:
    jsp:
      init-parameters:
        development : true
    encoding:
      force: true
      charset: UTF-8

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/llt
    username: root
    password: 1111
  mvc:
    view:
      prefix: /
      suffix: .jsp

logging:
  level:
    root: info
